config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailapp.urls", namespace="mailapp")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailapp/urls.py
from django.urls import path

from mailapp.apps import MailappConfig

from . import views

app_name = MailappConfig.name

urlpatterns = [
    path("", views.IndexTemplateView.as_view(), name="index"),
    path("recipient/", views.RecipientMailListViews.as_view(), name="recipient_list"),
    path("recipient/create/", views.RecipientMailCreateViews.as_view(), name="recipient_create"),
    path("recipient/detail/<int:pk>/", views.RecipientMailDetailViews.as_view(), name="recipient_detail"),
    path("recipient/update/<int:pk>/", views.RecipientMailUpdateViews.as_view(), name="recipient_update"),
    path("recipient/delete/<int:pk>/", views.RecipientMailDeleteViews.as_view(), name="recipient_delete"),
    path("message/create/", views.MailMessageCreateView.as_view(), name="create_message"),
    path("message/detail/<int:pk>/", views.MailMessageDetailView.as_view(), name="mail_message_detail"),
    path("message/update/<int:pk>/", views.MailMessageUpdateView.as_view(), name="mail_update_message"),
    path("message/delete/<int:pk>/", views.MailMessageDeleteView.as_view(), name="mail_delete_message"),
    path("message/list/", views.MailMessageListView.as_view(), name="mail_message_list"),
    path("attempts/", views.MailingAttemptListView.as_view(), name="mailing_attempts"),
    path("mailing/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailing/create/", views.MailingCreateView.as_view(), name="create_mailing"),
    path("mailing/detail/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/update/<int:pk>/", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/delete/<int:pk>/", views.MailingDeleteView.as_view(), name="mailing_delete"),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import UserCreateView, email_verification, UserProfileUpdateView, UserProfileDetailView, UsersListView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path(
        "reset_password/",
        PasswordResetView.as_view(
            template_name="users/registration/password_reset_form.html",
            email_template_name="users/registration/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>",
        PasswordResetConfirmView.as_view(
            template_name="users/registration/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("verify/<str:verification_token>/", email_verification, name="verify_email"),
    path("profile/<int:pk>/", UserProfileDetailView.as_view(), name="profile_detail"),
    path("profile/edit/<int:pk>/", UserProfileUpdateView.as_view(), name="edit_profile"),
    path("list/", UsersListView.as_view(), name="user_list"),
]

mailapp/forms.py
from django import forms
from email_validator import EmailNotValidError, validate_email

from .models import Mailing, MailMessage, RecipientMail


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({"class": "form-check-input"})
            else:
                field.widget.attrs.update({"class": "form-control"})


class RecipientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = RecipientMail
        fields = ["email", "full_name", "comment"]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            validate_email(email)
        except EmailNotValidError as e:
            raise forms.ValidationError(str(e))
        return email


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ["message", "recipients", "frequency"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields["recipients"].queryset = RecipientMail.objects.filter(owner=user)
            self.fields["message"].queryset = MailMessage.objects.filter(owner=user)

    def clean_recipients(self):
        recipients = self.cleaned_data.get("recipients")
        if not recipients:
            raise forms.ValidationError("Вы должны указать получателей.")
        return recipients


class MailMessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailMessage
        fields = ["subject", "body"]

mailapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from .forms import MailingForm, MailMessageForm, RecipientForm
from .models import Mailing, MailingAttempt, MailMessage, RecipientMail
from .services import MailingService


@method_decorator(cache_page(60 * 5), name="dispatch")  # Cache for 5 minutes
class IndexTemplateView(TemplateView):
    template_name = "mailapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.has_perm("mailapp.can_view_mailing"):
            context["count_mailing"] = Mailing.objects.all().count()
            context["count_active_mailing"] = Mailing.objects.filter(status="Запущена").count()
            context["count_unique_recipients"] = RecipientMail.objects.distinct().count()
            return context
        else:
            context["count_mailing"] = Mailing.objects.filter(owner=self.request.user).count()
            context["count_active_mailing"] = Mailing.objects.filter(
                status="Запущена", owner=self.request.user
            ).count()
            context["count_unique_recipients"] = (
                RecipientMail.objects.filter(owner=self.request.user).distinct().count()
            )
            return context


class RecipientMailListViews(LoginRequiredMixin, ListView):
    model = RecipientMail
    template_name = "mailapp/recipient_mail_list.html"
    context_object_name = "recipients"
    paginate_by = 10
    ordering = ["full_name"]

    def get_queryset(self):
        cached_recipients = cache.get("recipients")
        if cached_recipients:
            return cached_recipients
        # Если кэша нет, получаем объекты из базы и кешируем их
        recipients = RecipientMail.objects.all()
        cache.set("recipients", recipients, 60 * 5)  # Кэшируем на 5 минут
        user = self.request.user
        if user.has_perm("mailapp.can_view_recipient_mail"):
            return RecipientMail.objects.all()
        return RecipientMail.objects.filter(owner=user)


@method_decorator(cache_page(60 * 5), name="dispatch")  # Cache for 5 minutes
class RecipientMailDetailViews(LoginRequiredMixin, DetailView):
    model = RecipientMail
    template_name = "mailapp/recipient_mail_detail.html"
    context_object_name = "recipient"


class RecipientMailCreateViews(LoginRequiredMixin, CreateView):
    model = RecipientMail
    form_class = RecipientForm
    template_name = "mailapp/recipient_mail_form.html"
    success_url = reverse_lazy("mailapp:recipient_list")

    def form_valid(self, form):
        recipient = form.save(commit=False)
        recipient.owner = self.request.user
        recipient.save()
        return redirect(reverse("mailapp:recipient_detail", kwargs={"pk": recipient.pk}))


class RecipientMailUpdateViews(LoginRequiredMixin, UpdateView):
    model = RecipientMail
    template_name = "mailapp/recipient_mail_form.html"
    fields = ["email", "full_name", "comment"]
    success_url = reverse_lazy("mailapp:recipient_detail")

    def get_success_url(self):
        recipient = self.object
        return reverse_lazy("mailapp:recipient_detail", kwargs={"pk": recipient.pk})


class RecipientMailDeleteViews(LoginRequiredMixin, DeleteView):
    model = RecipientMail
    context_object_name = "recipient"
    template_name = "mailapp/recipient_mail_confirm_delete.html"
    success_url = reverse_lazy("mailapp:recipient_list")


class MailMessageListView(LoginRequiredMixin, ListView):
    model = MailMessage
    template_name = "mailapp/mail_message_list.html"
    context_object_name = "messages"
    paginate_by = 10

    def get_queryset(self):
        cached_messages = cache.get("messages")
        if cached_messages:
            return cached_messages
        # Если кэша нет, получаем объекты из базы и кешируем их
        messages = MailMessage.objects.all()
        cache.set("messages", messages, 60 * 5)  # Кэшируем на 5 минут
        user = self.request.user
        if user.has_perm("mailapp.can_view_mail_message"):
            return MailMessage.objects.all()
        return MailMessage.objects.filter(owner=user)


class MailMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailMessage
    template_name = "mailapp/mail_message_form.html"
    form_class = MailMessageForm
    success_url = reverse_lazy("mailapp:mail_message_list")

    def form_valid(self, form):
        message = form.save(commit=False)
        message.owner = self.request.user
        message.save()
        return redirect(reverse("mailapp:mail_message_list"))


class MailMessageUpdateView(LoginRequiredMixin, UpdateView):
    model = MailMessage
    template_name = "mailapp/mail_message_form.html"
    form_class = MailMessageForm
    success_url = reverse_lazy("mailapp:mail_message_detail")

    def get_success_url(self):
        message = self.object
        return reverse_lazy("mailapp:mail_message_detail", kwargs={"pk": message.pk})


@method_decorator(cache_page(60 * 5), name="dispatch")  # Cache for 5 minutes
class MailMessageDetailView(LoginRequiredMixin, DetailView):
    model = MailMessage
    template_name = "mailapp/mail_message_detail.html"
    context_object_name = "message"


class MailMessageDeleteView(LoginRequiredMixin, DeleteView):
    model = MailMessage
    template_name = "mailapp/mail_message_confirm_delete.html"
    context_object_name = "message"
    success_url = reverse_lazy("mailapp:mail_message_list")


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    template_name = "mailapp/mailing_form.html"
    form_class = MailingForm
    success_url = reverse_lazy("mailapp:mailing_list")

    def form_valid(self, form):
        mailing = form.save(commit=False)
        mailing.owner = self.request.user
        mailing.save()
        return redirect(reverse("mailapp:mailing_list"))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


@method_decorator(cache_page(60 * 5), name="dispatch")  # Cache for 5 minutes
class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = "mailapp/mailing_detail.html"
    context_object_name = "mailing"

    def post(self, request, *args, **kwargs):
        mailing = get_object_or_404(Mailing, pk=kwargs.get("pk"))
        if mailing.status == "Создана":
            MailingService.start_mailing(mailing)
            return redirect(reverse("mailapp:mailing_attempts"))
        elif mailing.status == "Запущена":
            if self.request.user.has_perm("mailapp.can_disabling_mailing") or self.request.user == mailing.owner:
                MailingService.stop_mailing(mailing)
                return redirect(reverse("mailapp:mailing_list"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipients"] = RecipientMail.objects.filter(mailing=self.object)
        return context


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    template_name = "mailapp/mailing_form.html"
    form_class = MailingForm
    success_url = reverse_lazy("mailapp:mailing_detail")

    def get_success_url(self):
        mailing = self.object
        return reverse_lazy("mailapp:mailing_detail", kwargs={"pk": mailing.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = "mailapp/mailing_list.html"
    context_object_name = "mailings"
    paginate_by = 10

    def get_queryset(self):
        cached_mailings = cache.get("mailings")
        if cached_mailings:
            return cached_mailings
        # Если кэша нет, получаем объекты из базы и кешируем их
        mailings = Mailing.objects.all()
        cache.set("mailings", mailings, 60 * 5)  # Кэшируем на 5 минут
        queryset = super().get_queryset()
        if self.request.user.has_perm("mailapp.can_view_mailing"):
            return Mailing.objects.all()
        return queryset.filter(owner=self.request.user)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    context_object_name = "mailing"
    template_name = "mailapp/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailapp:mailing_list")


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = "mailapp/mailing_attempt_list.html"
    context_object_name = "attempts"
    paginate_by = 10
    ordering = ["-date_mailing"]

    def get_queryset(self):
        cached_attempts = cache.get("attempts")
        if cached_attempts:
            return cached_attempts
        # Если кэша нет, получаем объекты из базы и кешируем их
        attempts = MailingAttempt.objects.all()
        cache.set("attempts", attempts, 60 * 5)  # Кэшируем на 5 минут
        queryset = super().get_queryset()
        return queryset.filter(mailing__owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.has_perm("mailapp.can_view_mailing_attempt"):
            context["total_sent_messages"] = MailingAttempt.objects.filter(status="Успешно").count()
            context["total_failed_messages"] = MailingAttempt.objects.filter(status="Не успешно").count()
            return context
        else:
            context["total_sent_messages"] = MailingAttempt.objects.filter(
                status="Успешно", mailing__owner=self.request.user

mailapp/templates/mailapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылок</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <style>
        {
        box-sizing: border-box;
        }

        html, body {
        width: 100%;
        height: 100%;
        }
        body {
        margin: 0;
        }
    </style>
</head>
<header>{% include 'mailapp/includes/inc_menu.html' %}</header>
<body>
<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="sticky-bottom">
    <p class="text-center text-body-secondary">&copy; 2025 MailApp. Все права защищены.</p>
</footer>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailapp/templates/mailapp/index.html
{% extends 'mailapp/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1>Главная страница</h1>
    <p>Добро пожаловать в приложение для создания и рассылки электронных писем.</p>
    <h2>Статистика</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Всего рассылок</th>
                <th scope="col">Активных рассылок</th>
                <th scope="col">Уникальных получателей</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row"></th>
                <td>{{ count_mailing }}</td>
                <td>{{ count_active_mailing }}</td>
                <td>{{ count_unique_recipients }}</td>
            </tr>
        </tbody>
    </table>
{% else %}
<h1>Добро пожаловать в приложение для создания и рассылки электронных писем!</h1>
<p>Чтобы начать использовать приложение, войдите в систему с помощью своего аккаунта.</p>
<a class="btn btn-primary" href="{% url 'users:login' %}">Войти</a>
<p>Еще не зарегистрированы? <a href="{% url 'users:register' %}">Регистрация</a></p>
{% endif %}
{% endblock %}

mailapp/templates/mailapp/mail_message_confirm_delete.html
{% extends 'mailapp/base.html' %}

{% block title %}Удалить сообщение{% endblock %}

{% block content %}
<h1>Удаление сообщения</h1>

<p>Вы уверены, что хотите удалить сообщение с текстом: <strong>{{ message.body }}</strong>?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger">Удалить</button>
    <a href="{% url 'mailapp:mail_message_detail' message.pk %} " class="btn btn-outline-secondary">Отмена</a>
</form>
{% endblock %}

mailapp/templates/mailapp/mail_message_detail.html
{% extends 'mailapp/base.html' %}

{% block title %}Детали сообщения{% endblock %}

{% block content %}
<h1>Детали сообщения</h1>

<h4>Тема: {{ message.subject }}</h4>
<h5>Текст сообщения:</h5>
<p>{{ message.body }}</p>


<a href="{% url 'mailapp:mail_delete_message' message.pk %}" class="btn btn-outline-danger">Удалить сообщение</a>
<a href="{% url 'mailapp:mail_update_message' message.pk %}" class="btn btn-outline-warning">Изменить сообщение</a>
<a href="{% url 'mailapp:mail_message_list' %}" class="btn btn-outline-primary">Назад к списку сообщений</a>
{% endblock %}

mailapp/templates/mailapp/mail_message_form.html
{% extends 'mailapp/base.html' %}

{% block title %}Форма сообщения{% endblock %}

{% block content %}
{% if object %}
  <h1>Изменить сообщение</h1>
{% else %}
  <h1>Новое сообщение</h1>
{% endif %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-success">Сохранить</button>
  <a href="{% url 'mailapp:mail_message_list' %} " class="btn btn-outline-secondary">Отмена</a>
</form>
{% endblock %}

mailapp/templates/mailapp/mail_message_list.html
{% extends 'mailapp/base.html' %}

{% block title %}Список сообщений{% endblock %}

{% block content %}
<h1>Список сообщений</h1>
<p>В этом списке находятся все сообщения, которые были отправлены в вашу почтовую рассылку.</p>
{% if messages %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Тема</th>
            <th scope="col">Содержание</th>
        </tr>
        </thead>
        <tbody>
    {% for message in messages %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ message.subject }}</td>
            <td>{{ message.body|truncatechars:50 }}</td>
            <td><a href="{% url 'mailapp:mail_message_detail' message.pk %}">Подробнее</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>Ваш список сообщений пуст.</p>
{% endif %}
<a href="{% url 'mailapp:create_message' %}" class="btn btn-outline-primary">Создать сообщение</a>
<center>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
    {% endif %}
    &nbsp; &nbsp;
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    &nbsp; &nbsp;
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
    {% endif %}
</center>
{% endblock %}

mailapp/templates/mailapp/mailing_attempt_list.html
{% extends 'mailapp/base.html' %}

{% block title %}Попытки отправок{% endblock %}

{% block content %}
<h1>Попытки отправок</h1>
<p>В этом списке находятся все попытки отправки сообщений в вашу почтовую рассылку.</p>

{% if attempts %}
<p>Успешных отправок: {{ total_sent_messages }}</p>
<p>Неуспешных отправок: {{ total_failed_messages }}</p>
<p>Количество отправленных сообщений: {{ total_sent_messages }}</p>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Дата и время попытки</th>
        <th scope="col">Ответ почтового сервера</th>
        <th scope="col">Статус попытки</th>
        <th scope="col">Рассылка</th>
    </tr>
    </thead>
    <tbody>
    {% for attempt in attempts %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ attempt.date_mailing }}</td>
        <td>{{ attempt.mail_server_response }}</td>
        <td>{{ attempt.status }}</td>
        <td>{{ attempt.mailing }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Ваш список попыток отправок пуст.</p>
{% endif %}
<center>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
    {% endif %}
    &nbsp; &nbsp;
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    &nbsp; &nbsp;
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
    {% endif %}
</center>


{% endblock %}

mailapp/templates/mailapp/mailing_detail.html
{% extends 'mailapp/base.html' %}

{% block title %}Информация о рассылке{% endblock %}

{% block content %}
<h1>Информация о рассылке</h1>

<div class="card">
    <div class="card-body">
        <p class="card-text">Дата и время первой отправки: {{ mailing.start_time }}</p>
        <p class="card-text">Дата и время последней отправки: {{ mailing.end_time }}</p>
        <p class="card-text">Статус рассылки: {{ mailing.status }}</p>
        <p class="card-text">Сообщение: {{ mailing.message }}</p>
        <p class="card-text">Частота рассылки: {{ mailing.frequency }}</p>
        <p class="card-text">Получатели:
            {% for recipient in recipients %}
            {{ recipient.email }},
            {% endfor %}
        </p>
        {% if mailing.status == 'Создана' and user == mailing.owner %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success">Run mailing</button>
        </form>
        {% elif mailing.status == 'Запущена' and user == mailing.owner or perms.can_disabling_mailing %}
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Stop mailing</button>
            </form>
        {% endif %}
        <a href="{% url 'mailapp:mailing_list' %}" class="btn btn-primary">К списку рассылок</a>
        {% if user == mailing.owner %}
        <a href="{% url 'mailapp:mailing_update' mailing.pk %}" class="btn btn-warning">Изменить данные</a>
        <a href="{% url 'mailapp:mailing_delete' mailing.pk %}" class="btn btn-danger">Удалить рассылку</a>
        {% endif %}
    </div>
</div>
{% endblock %}

mailapp/templates/mailapp/mailing_list.html
{% extends 'mailapp/base.html' %}

{% block title %}Список рассылок{% endblock %}

{% block content %}
<h1>Список рассылок</h1>
<p>В этом списке находятся все рассылки, которые были созданы вами.</p>

{% if mailings %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Дата и время первой отправки</th>
            <th scope="col">Дата и время последней отправки</th>
            <th scope="col">Статус рассылки</th>
            <th scope="col">Сообщение</th>
            <th scope="col">Частота рассылки</th>
          </tr>
        </thead>

        <tbody>

        {% for mailing in mailings %}
          <tr>
            <th scope="row">{{ mailing.pk }}</th>
            <td>{{ mailing.start_time }}</td>
            <td>{{ mailing.end_time }}</td>
            <td>{{ mailing.status }}</td>
            <td>{{ mailing.message|truncatechars:100 }}</td>
            <td>{{ mailing.frequency }}</td>
            <td><a href="{% url 'mailapp:mailing_detail' mailing.pk %}">Подробнее</a></td>
          </tr>
        {% endfor %}

        </tbody>
      </table>

{% else %}
    <p>Ваш список рассылок пуст.</p>
{% endif %}

<a href="{% url 'mailapp:create_mailing' %}" class="btn btn-outline-primary">Создать рассылку</a>
<center>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
    {% endif %}
    &nbsp; &nbsp;
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    &nbsp; &nbsp;
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
    {% endif %}
    </center>
{% endblock %}

mailapp/templates/mailapp/recipient_mail_list.html
{% extends 'mailapp/base.html' %}

{% block title %}Список получателей{% endblock %}

{% block content %}
<h1>Список получателей</h1>
<p>В этом списке находятся все адреса электронной почты, которые были добавлены в ваш список рассылки.</p>

{% if recipients %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Адрес электронной почты</th>
            <th scope="col">Ф.И.О.</th>
            <th scope="col">Комментарий</th>
        </tr>
    </thead>
    <tbody>
    {% for recipient in recipients %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ recipient.email }}</td>
            <td>{{ recipient.full_name }}</td>
            <td>{{ recipient.comment|truncatechars:50 }}</td>
            <td><a href="{% url 'mailapp:recipient_detail' recipient.pk %}">Подробнее</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Ваш список получателей пуст.</p>
{% endif %}
<a href="{% url 'mailapp:recipient_create' %}" class="btn btn-outline-primary">Добавить получателя</a>
<center>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
    {% endif %}
    &nbsp; &nbsp;
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    &nbsp; &nbsp;
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
    {% endif %}
</center>
{% endblock %}