config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailapp.urls", namespace="mailapp")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import UserCreateView, email_verification, UserProfileUpdateView, UserProfileDetailView, UsersListView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path(
        "reset_password/",
        PasswordResetView.as_view(
            template_name="users/registration/password_reset_form.html",
            email_template_name="users/registration/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>",
        PasswordResetConfirmView.as_view(
            template_name="users/registration/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("verify/<str:verification_token>/", email_verification, name="verify_email"),
    path("profile/<int:pk>/", UserProfileDetailView.as_view(), name="profile_detail"),
    path("profile/edit/<int:pk>/", UserProfileUpdateView.as_view(), name="edit_profile"),
    path("list/", UsersListView.as_view(), name="user_list"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    area = models.CharField(max_length=50, blank=True, null=True)
    verification_token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [("can_view_user_list", "Can view user list"), ("can_blocking_user", "Can blocking user")]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from email_validator import EmailNotValidError, validate_email

from .models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.EmailField):
                field.widget.attrs.update({"class": "form-control", "type": "email"})
            elif isinstance(field, forms.ImageField):
                field.widget.attrs.update({"class": "form-control", "type": "file"})
            elif isinstance(field, forms.BooleanField):
                field.widget.attrs.update({"class": "form-check-input"})
            else:
                field.widget.attrs.update({"class": "form-control"})


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "avatar", "phone_number", "area", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            validate_email(email)
        except EmailNotValidError as e:
            raise forms.ValidationError(str(e))
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры.")
        return phone_number


class UserEditForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "avatar", "phone_number", "area")
        exclude = ("password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            validate_email(email)
        except EmailNotValidError as e:
            raise forms.ValidationError(str(e))
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры.")
        return phone_number


class UserManagerEditForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ("is_active",)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import UserEditForm, UserManagerEditForm, UserRegisterForm
from .models import User
from .services import UserService


class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    template_name = "users/user_list.html"
    permission_required = "users.can_view_user_list"
    context_object_name = "users"

    def get_queryset(self):
        return super().get_queryset().filter(is_staff=False)


class UserCreateView(CreateView):
    template_name = "users/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        host = self.request.get_host()
        UserService.send_verification_email(user, host)
        return super().form_valid(form)


def email_verification(request, verification_token):
    user = get_object_or_404(User, verification_token=verification_token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserProfileUpdateView(UpdateView):
    model = User
    form_class = UserEditForm
    template_name = "users/profile_edit.html"
    login_url = reverse_lazy("users:login")
    success_url = reverse_lazy("users:profile_detail")
    context_object_name = "user"

    def get_success_url(self):
        return reverse("users:profile_detail", kwargs={"pk": self.kwargs["pk"]})

    def get_form_class(self):
        if self.request.user.has_perm("users.can_blocking_user"):
            return UserManagerEditForm
        else:
            return UserEditForm


@method_decorator(cache_page(60 * 5), name="dispatch")  # Cache for 5 minutes
class UserProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/profile_detail.html"
    login_url = reverse_lazy("users:login")
    context_object_name = "user"

users/templates/users/login.html
{% extends 'mailapp/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Вход</h1>
            <form method="POST" class="form-control">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Войти</button>
            </form>
            <p class="text-center">Еще не зарегистрированы? <a href="{% url 'users:register' %}">Регистрация</a></p>
            <p class="text-center">Забыли пароль? <a href="{% url 'users:reset_password' %}">Восстановить пароль</a></p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_detail.html
{% extends 'mailapp/base.html' %}
{% load my_tags %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <img src="{{ user.avatar | media_filter }}" class="img-fluid rounded-start" alt="{{user.email}}">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                <h6>Телефон: {{ user.phone_number }} </h6>
                <h6>Email: {{ user.email }}</h6>
                <p>Дата регистрации: {{ user.date_joined }}</p>
                <p>Страна: {{ user.area }}</p>
                <a href="{% url 'users:edit_profile' user.pk %}" class="btn btn-primary mt-3">Изменить профиль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'mailapp/base.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Редактировать профиль</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Сохранить изменения</button>
            </form>
            <a href="{% url 'users:profile_detail' user.pk %}" class="btn btn-secondary m-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailapp/base.html' %}

{% block title %}Регистрация пользователя{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Регистрация</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Регистрация</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailapp/base.html' %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
<h1>Список пользователей</h1>
<p>В этом списке находятся все зарегистрированные пользователи в системе.</p>

{% if users %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Дата регистрации</th>
                <th scope="col">Страна</th>
                <th scope="col">Активный</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ user.email }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.date_joined }}</td>
                <td>{{ user.area }}</td>
                <td>{{ user.is_active|yesno:"Да,Нет" }}</td>
                <td><a href="{% url 'users:profile_detail' user.pk %}">Подробнее</a></td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
{% else %}
    <p>В системе нет зарегистрированных пользователей.</p>
{% endif %}
{% endblock %}